version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    command: ["./entrypoint.sh", "python", "manage.py", "runserver", "0.0.0.0:8000"]

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: trazabilidad_db
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: clave123
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data  # Monta un volumen local para la primera base de datos
